version: '3.7'
services:
  php:
    build: ./docker/php
    ports: ['9000:9000']
    volumes: ['./:/var/www:cached']
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.0.33"
      PHP_IDE_CONFIG: "serverName=weather.local"
      
  nginx:
    build: ./docker/nginx
    ports: ['8002:80']
    volumes: ['./public:/var/www/public:cached']